name: elevate_config_annotation
description: Annotations for elevate_config_generation
version: 0.0.1
repository: https://github.com/Hexsis/elevate/tree/main/packages/elevate_config_annotation

environment:
  sdk: '>=2.19.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
